### ISSUE TITLE
Can't download test data

### ISSUE THREAD

**Issue by robi56** [sharibox/EAD2019#10]
Hi, I have registered to the challenge. I want to test my segmentation model but I can't download the dataset by run 'python downloads/test_data_download.py'

**Comment by sharib-vision** [comment]
those links has been temporarily disables. Please download it here. https://data.mendeley.com/datasets/c7fjbxcgj9/2

**Comment by kimdinhthaibk** [comment]
> those links has been temporarily disables. Please download it here. https://data.mendeley.com/datasets/c7fjbxcgj9/2
Hi sharibox, I just saw train dataset for detection and segmentation, not seeing the TEST dataset. Can you send me the link of test dataset? Thanks.

**Comment by libingyang0** [comment]
I can't download test data,too. Could you send me the link of test data? 
Thank you very much!
