### ISSUE TITLE
issue in downloading test data

### ISSUE THREAD

**Issue by errorHandling** [sharibox/EAD2019#11]
I am not able to download test data. After running the python code to download the test data,I got the error which is : BadZipFile: File is not a zip file

**Comment by GorkemP** [comment]
https://github.com/sharibox/EAD2019/issues/10#issuecomment-505218817

**Comment by jhx9327** [comment]
Hi, GorkemP. At https://data.mendeley.com/datasets/c7fjbxcgj9/2, there are only trainingData_detection.zip and trainingData_semanticSegmentation.zip. Do you know how to get the TEST dataset? Thanks a lot. @GorkemP

**Comment by GorkemP** [comment]
Hi, it seems that test data for EAD2019 is not available right now. Maybe @sharibox can update us about this issue.

**Comment by sharib-vision** [comment]
Dear all, 

We have now released a newer version of this dataset as EAD2020 (https://ead2020.grand-challenge.org). This data now is updated including corrections for some bounding boxes that were with error in the previous data release. Additionally, it also supplies more samples. Regarding the test samples we do not post it online and they are available only for participants. As EAD2020 is now open, we discourage test on our previous release so at the moment we will not be able to provide you this. Please enrol to the EAD2020 challenge for which training data are already available. Test dataset will follow.  Thank you all for your participation. Best wishes,

**Comment by GorkemP** [comment]
Hi Sharib, so for now we have only 2200+99 frames for object detection (and more (sequence frame annotation) is coming)?

**Comment by sharib-vision** [comment]
Hi GorkemP, 
yes, if everything goes fine we will soon release few sequence data. We will try to release both semantic and bounding boxes for this as we are aware of small number of semantic data size
