### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by akhanss** [sharibox/EAD2019#2]
Thank you for arranging a great challenge and a valuable repo. I am just wondering if you can provide an example of the bounding box in (xmin, ymin, xmax, ymax) format. 

I have confusion whether it is really given in <x, y, width, height> according to the documentation. When I convert normalized version to absolute version (xmin, ymin, xmax, ymax), it seems that ROIs are pointing to the different things.

BTW, I am a participant of the challenge. Thank you in advance.

Cheers,
- Azam.

**Comment by fyz11** [comment]
Hi Azam,

I updated the repo with a new folder called "examples". Inside there is a python script which illustrates how to extract and plot the bounding boxes. 

Best,

Felix

**Comment by akhanss** [comment]
Hi Felix,
Thnx a lot for your prompt reply. Yes, it is working as intended.
