### ISSUE TITLE
EAD比赛

### ISSUE THREAD

**Issue by wyxhahaha** [sharibox/EAD2019#5]
大神你好，想请问下，你也参加EAD比赛吗，能不能加个qq，讨论请教一下你，谢谢，我QQ  2932221844

**Comment by sharib-vision** [comment]
please follow google groups and ask your queries there. You can also ask related queries here but please use English as medium of communication. 

https://groups.google.com/forum/#!forum/ead2019-challenge

Thank you for your interest.
