### ISSUE TITLE
How to compute mAP for segmentation

### ISSUE THREAD

**Issue by cxxpython9** [sharibox/EAD2019#6]
A script 'compute_mAP_IoU.py' is used to compute mAP for detection. According to the method, 'confidence' is necessary to compute mAP. How to get it for the segmentation?

**Comment by wyxhahaha** [comment]
Hello， I am also a participant for the competition，have you ever solve the segmentation problems, because I found some problems in datasets.
I meet with same question with you，can you add me in WeChat for futher discussion. 13628640730. Thank you!

**Comment by sharib-vision** [comment]
hi,

please see here, this is relevant to your question: https://github.com/sharibox/EAD2019/issues/4#issue-402155377

For semantic, you will just need to generate masks and upload it the mask directly or a 'json' file corresponding to it. We are currently working on setting leaderboard with clear instructions.


best wishes,
