### ISSUE TITLE
Is the second task an instance segmentation one or semantic segmentation one?

### ISSUE THREAD

**Issue by cxxpython9** [sharibox/EAD2019#7]
'Instance segmentation' is mentioned in some places or some settings mean that it is an instance segmentation. For instance, mAP must be considered in the second task. However, it is never used to evaluate semantic segmentation.
According to the ground truth of the data, it is a semantic segmentation task. 
So, should we consider it as an instance segmentation task?

**Comment by sharib-vision** [comment]
Hi,
Sorry regarding the confusion. No this will not be an explicit instance segmentation but rather semantic plus detection. We want to cross-check if the semantic corresponds to the detected bounding boxes by the detection method or not. Participants will be required to upload masks and their corresponding bounding boxes to get the final score. 

I hope this is clear now.

Best wishes,

**Comment by cxxpython9** [comment]
Thank you for your detailed explanation.

**Comment by sharib-vision** [comment]
Great. I am closing this issue then.
