### ISSUE TITLE
Total number of bbox per class

### ISSUE THREAD

**Issue by akhanss** [sharibox/EAD2019#8]
Dear organizer,
As per information on GitHub, for task 1, the number of labels per class is as follows: 5511 (specularity), 1099 (saturation), 5015 (artifact), 658 (blur), 1532 (contrast), 2904 (bubbles), 437 (instrument). However, I found different numbers for the same (PhaseI: specularity (4074), saturation (511), artifact (1609), blur (327), contrast (686), bubbles (1738), instrument (407). If we consider both phase1 and phase2, the figures is as follows: specularity (7596), saturation (1733), artifact (8583), blur (1023), contrast (2430), bubbles (4420), instrument (499). I am just wondering if you can check and update the statistics. Thank you in advance.

Best wishes,
- Azam.

**Comment by fyz11** [comment]
Hi Azam, 

I have double checked and combining both detection phases over 2192 files we have:
5096 - artifact,
675 - blur
3079 - bubbles
1558 - contrast
453 - instrument
1122 - saturation
5835 - specularity

My counting of phase I is the same as yours.
Phase II release breakdown by my counting is:
3487 - artifact,
348 - blur
1341 - bubbles
872 - contrast
46 - instrument
611 - saturation
1761 - specularity

If you are happy with these numbers I will update the github to reflect the revised countings. 

Best,

Felix

**Comment by akhanss** [comment]
Yes, you are correct, Felix. Thank you for your prompt reply.

**Comment by fyz11** [comment]
thanks for confirming. I have updated to the corrected version.
