### ISSUE TITLE
Question of F2-score  

### ISSUE THREAD

**Issue by cxxpython9** [sharibox/EAD2019#9]
The new metric F2-score is released. However, I am confused of it.
According to the code,  we need to have the 'confusion_matrix' to get 'fp, tp and fn'. If the input of 'prediction and ground_truth' is of 5 channels, how to define the label of each channel? If the labels the 5 classes are defined as 255 while the backgrounds are 0, the 'confusion_matrix' is not right because only the bins of 0 and 1 have values. 
As as result, I guess the confusion_matrix should be based on a single channel and the 'nr_labels' should be 2.  
Thanks for your attention!

**Comment by sharib-vision** [comment]
Hi,

thank you for your observation. We have checked it and fixed the bug. 
We have uploaded the method and its available to be used for leaderboard scoring.

Best,
